# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Infant.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1311, 735)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 30, 641, 111))
        self.groupBox.setMinimumSize(QtCore.QSize(561, 91))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 601, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_realtime = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_realtime.setObjectName("btn_realtime")
        self.horizontalLayout.addWidget(self.btn_realtime)
        self.btn_input = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_input.setObjectName("btn_input")
        self.horizontalLayout.addWidget(self.btn_input)
        self.btn_pause = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayout.addWidget(self.btn_pause)
        self.btn_exportlog = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_exportlog.setObjectName("btn_exportlog")
        self.horizontalLayout.addWidget(self.btn_exportlog)
        self.btn_quit = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_quit.setObjectName("btn_quit")
        self.horizontalLayout.addWidget(self.btn_quit)
        self.recognition_results_label = QtWidgets.QLabel(self.centralwidget)
        self.recognition_results_label.setGeometry(QtCore.QRect(760, 330, 521, 41))
        self.recognition_results_label.setMinimumSize(QtCore.QSize(331, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.recognition_results_label.setFont(font)
        self.recognition_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.recognition_results_label.setObjectName("recognition_results_label")
        self.statistics_results_label = QtWidgets.QLabel(self.centralwidget)
        self.statistics_results_label.setGeometry(QtCore.QRect(760, 10, 521, 41))
        self.statistics_results_label.setMinimumSize(QtCore.QSize(331, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statistics_results_label.setFont(font)
        self.statistics_results_label.setAlignment(QtCore.Qt.AlignCenter)
        self.statistics_results_label.setObjectName("statistics_results_label")

        self.label_result = QtWidgets.QListWidget(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(760, 380, 521, 271))
        self.label_result.setObjectName("label_result")

        self.label_video = QtWidgets.QLabel(self.centralwidget)
        self.label_video.setGeometry(QtCore.QRect(40, 170, 691, 481))
        self.label_video.setText("")
        self.label_video.setObjectName("label_video")

        self.label_statistic = QtWidgets.QLabel(self.centralwidget)
        self.label_statistic.setGeometry(QtCore.QRect(750, 50, 531, 271))
        self.label_statistic.setObjectName("label_statistic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1311, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "功能选择区"))
        self.btn_realtime.setText(_translate("MainWindow", "实时监测"))
        self.btn_input.setText(_translate("MainWindow", "加载视频"))
        self.btn_pause.setText(_translate("MainWindow", "暂停"))
        self.btn_exportlog.setText(_translate("MainWindow", "导出日志"))
        self.btn_quit.setText(_translate("MainWindow", "退出系统"))
        self.recognition_results_label.setText(_translate("MainWindow", "识别结果"))
        self.statistics_results_label.setText(_translate("MainWindow", "统计结果"))

